/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.9.20"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

java {
    toolchain {
        setSourceCompatibility(JavaLanguageVersion.of(21))
        setTargetCompatibility(JavaLanguageVersion.of(21))
    }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation(platform("org.springframework.boot:spring-boot-dependencies:3.2.2"))
    implementation("org.springframework.boot", "spring-boot-starter-web")
    implementation("org.springframework.kafka:spring-kafka:3.1.1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.1")


    testImplementation("org.testcontainers:kafka:1.19.4")
    testImplementation("org.testcontainers:junit-jupiter:1.19.4")

    runtimeOnly("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.3")
}
